name: Email Reminder Service

on:
  schedule:
    - cron: "0 8 * * *" # Runs daily at 8 AM UTC
  workflow_dispatch: # Allows manual trigger

jobs:
  send-reminders:
    runs-on: ubuntu-latest # Keep using Ubuntu for now, adjust if switching to matrix strategy later

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10" # Use Python 3.9, adjust as needed (ensure compatibility with dependencies)

      - name: Check Python version
        run: python --version # Verify the Python version installed in the runner

      - name: Create and activate virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate  # Use the appropriate activation command for Ubuntu (Linux)

      - name: Upgrade pip and install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install --no-cache-dir -r requirements.txt || pip install -r requirements.txt --no-deps

      - name: List installed packages
        run: |
          pip list  # Confirm that the required packages are installed

      - name: Create credentials file
        run: |
          echo "${{ secrets.GMAIL_CREDENTIALS }}" > client_secret.json  # Store Gmail credentials from secrets

      - name: Run the script
        env:
          SHEET_ID: ${{ secrets.SHEET_ID }} # Pass the secret for Google Sheets ID
        run: python main.py # Run the main Python script
