name: Email Reminder Service

on:
  schedule:
    - cron: "0 8 * * *" # Runs daily at 8 AM UTC
  workflow_dispatch: # Allows manual trigger

  jobs:
  send-reminders:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      # Remove the step for installing pywin32 (if not needed)
      # - name: Install dependencies
      #   run: |
      #     python -m pip install --upgrade pip setuptools wheel
      #     pip install --no-cache-dir -r requirements.txt || pip install -r requirements.txt --no-deps

      # ... rest of the steps
jobs:
  send-reminders:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install --no-cache-dir -r requirements.txt || pip install -r requirements.txt --no-deps

      - name: List installed packages
        run: |
          pip list

      - name: Create credentials file
        run: |
          echo "${{ secrets.GMAIL_CREDENTIALS }}" > client_secret.json

      - name: Run script
        env:
          SHEET_ID: ${{ secrets.SHEET_ID }}
        run: python main.py
