name: Email Reminder Service

on:
  schedule:
    - cron: "0 8 * * *" # Runs daily at 8 AM UTC
  workflow_dispatch: # Allows manual trigger

jobs:
  send-reminders:
    runs-on: ubuntu-latest # Keep using Ubuntu for now, adjust if switching to matrix strategy later

    steps:
      - name: Checkout code
        uses: actions/checkout@v3 # Updated to v3

      - name: Set up Python
        uses: actions/setup-python@v4 # Updated to v4
        with:
          python-version: "3.9" # Ensure Python version is compatible

      - name: Set up Node.js
        uses: actions/setup-node@v3 # Updated to v3
        with:
          node-version: "16" # Ensure Node.js version is compatible

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --no-cache-dir -r requirements.txt

      - name: Create credentials file
        run: |
          echo "${{ secrets.GMAIL_CREDENTIALS }}" > client_secret.json # Store Gmail credentials

      - name: Run the script
        env:
          SHEET_ID: ${{ secrets.SHEET_ID }} # Pass Google Sheets ID as an environment variable
        run: python main.py # Run the script
